# ######################################################################### ########################
#                 НЕ УДАЛЯЙТЕ И НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ #
# Этот файл сгенерирован автоматически и используется для запуска тестов #
#                                                                         #
#                     НЕ УДАЛЯЙТЕ И НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ #
#      Этот файл создается автоматически и используется для запуска тестов #
# ######################################################################### ########################

имя : гекслет-чек

на :
  нажать :
    филиалы :
      - ' ** '
    теги :
      - ' ** '

вакансии :
  сборка :
    запускается : ubuntu-latest
    шаги :
      - использует : actions / checkout @ v2

      - название : Проверка проекта Hexlet
        использует : hexlet / project-action @ release
        с :
          идентификатор-шестнадцатеричный : $ {{secrets.HEXLET_ID}}
